name = "handbook-auth-worker"
main = "src/index.ts"
compatibility_date = "2024-08-31"

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "handbook-db"
database_id = "900577dd-598f-4c39-b753-e9fe436b29f4"

# KV Bindings
[[kv_namespaces]]
binding = "SESSIONS_KV"
id = "sessions_kv_namespace"
preview_id = "sessions_kv_namespace_preview"

[[kv_namespaces]]
binding = "CACHE_KV"
id = "cache_kv_namespace"
preview_id = "cache_kv_namespace_preview"

# Queue Binding
[[queues.producers]]
binding = "EMAIL_QUEUE"
queue = "email-processing"

# Development environment
[env.development]
workers_dev = true

[env.development.vars]
ENVIRONMENT = "development"
FRONTEND_URL = "http://localhost:3000"

# Production environment
[env.production]
workers_dev = false

[env.production.vars]
ENVIRONMENT = "production"
FRONTEND_URL = "https://yourhandbook.com"
