name = "handbook-email-worker"
main = "src/index.ts"
compatibility_date = "2024-08-31"

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "handbook-db"
database_id = "900577dd-598f-4c39-b753-e9fe436b29f4"

# KV Bindings
[[kv_namespaces]]
binding = "CACHE_KV"
id = "b39637e739454ae1a775f714ce7c3200"

[[kv_namespaces]]
binding = "ANALYTICS_KV"
id = "2bf5049d1b994fb3bd9093828581ec64"

# Queue Binding (Disabled for free plan)
# [[queues.producers]]
# binding = "EMAIL_QUEUE"
# queue = "email-processing"

# Queue Consumer (Disabled for free plan)
# [[queues.consumers]]
# queue = "email-processing"
# max_batch_size = 10
# max_batch_timeout = 30

# Development environment
[env.development]
workers_dev = true

[env.development.vars]
ENVIRONMENT = "development"
FRONTEND_URL = "http://localhost:3000"

# Production environment
[env.production]
workers_dev = false

[env.production.vars]
ENVIRONMENT = "production"
FRONTEND_URL = "https://yourhandbook.com"
